export {default as Main} from './Main'
export {default as Navbar} from './Navbar'
export {default as Home} from './Home'
export {default as Resume} from './Resume'
export {default as Projects} from './Projects'
export {default as Footer} from './Footer'